source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.3'

target 'WeShot' do
pod 'AFNetworking', '~> 3.0'
pod 'SVProgressHUD'
pod 'MJExtension'
pod 'SDWebImage', '~>3.8'
pod 'MJRefresh'
end
